### PR TITLE
GroupedNativeMethodsGenerator: generate attributes on extension methods where applicable

### PR DESCRIPTION
**Pull request by Xpl0itR**
Adds the following attributes where applicable:
- MethodImplAttribute with AggressiveInlining hint to generated extension methods
- ~~GeneratedCodeAttribute to generated extensions class~~
- ObsoleteAttribute to generated extension methods where the native method binding is also marked Obsolete

### CODE REVIEW

**Comment by neuecc** [comment]
Thank you.
`GeneratedCodeAttribute` is for CodeDom and is an old one, isn't it?
For things like AggressiveInlining that are generated, the JIT should perform it automatically, so I think it's not necessary to explicitly specify it.

**Comment by Xpl0itR** [comment]
`GeneratedCodeAttribute` is useful for tools that operate on the assembly rather than the source file because they won't see the `// <auto-generated/>` header. It is still used by Microsoft in their source generators, like [System.Text.Json](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L166) for example.

Similarly, Microsoft explicitly use AggressiveInlining in the standard libraries like the [Unsafe.AsPointer](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/Unsafe.cs#L34) for example.

**Comment by neuecc** [comment]
Hmmm, I still can't accept CodeDom Namespace.

**Comment by Xpl0itR** [comment]
@neuecc OK, I have dropped that commit

**Comment by neuecc** [comment]
thanks, I'll release soon.

**Pull request merged**
